/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author 1gdaw09
 */
public class CrearEquipos extends javax.swing.JFrame {

    /**
     * Creates new form CrearEquipos
     */
    public CrearEquipos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloCrearEquipos = new javax.swing.JLabel();
        LNombredelequipo = new javax.swing.JLabel();
        LDueño = new javax.swing.JLabel();
        LJugador1 = new javax.swing.JLabel();
        LJugador2 = new javax.swing.JLabel();
        LJugador3 = new javax.swing.JLabel();
        LJugador4 = new javax.swing.JLabel();
        LJugador5 = new javax.swing.JLabel();
        LReserva = new javax.swing.JLabel();
        TNombredelequipo = new javax.swing.JTextField();
        TDueño = new javax.swing.JTextField();
        Tjugador1 = new javax.swing.JTextField();
        Tjugador2 = new javax.swing.JTextField();
        Tjugador3 = new javax.swing.JTextField();
        Tjugador4 = new javax.swing.JTextField();
        Tjugador5 = new javax.swing.JTextField();
        TReserva = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TituloCrearEquipos.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        TituloCrearEquipos.setText("Crear equipos");

        LNombredelequipo.setText("Nombre del equipo");

        LDueño.setText("Dueño");

        LJugador1.setText("Jugador 1");

        LJugador2.setText("Jugador 2");

        LJugador3.setText("Jugador 3");

        LJugador4.setText("Jugador 4");

        LJugador5.setText("Jugador 5");

        LReserva.setText("Reserva");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LNombredelequipo)
                    .addComponent(LDueño, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJugador1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJugador2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJugador3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJugador4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LJugador5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LReserva, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TDueño)
                    .addComponent(TNombredelequipo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(TReserva, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Tjugador5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Tjugador4, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Tjugador2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Tjugador1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Tjugador3, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TituloCrearEquipos, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(TituloCrearEquipos)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LNombredelequipo)
                    .addComponent(TNombredelequipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LDueño)
                    .addComponent(TDueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJugador1)
                    .addComponent(Tjugador1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJugador2)
                    .addComponent(Tjugador2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJugador3)
                    .addComponent(Tjugador3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJugador4)
                    .addComponent(Tjugador4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LJugador5)
                    .addComponent(Tjugador5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LReserva)
                    .addComponent(TReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEquipos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEquipos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LDueño;
    private javax.swing.JLabel LJugador1;
    private javax.swing.JLabel LJugador2;
    private javax.swing.JLabel LJugador3;
    private javax.swing.JLabel LJugador4;
    private javax.swing.JLabel LJugador5;
    private javax.swing.JLabel LNombredelequipo;
    private javax.swing.JLabel LReserva;
    private javax.swing.JTextField TDueño;
    private javax.swing.JTextField TNombredelequipo;
    private javax.swing.JTextField TReserva;
    private javax.swing.JLabel TituloCrearEquipos;
    private javax.swing.JTextField Tjugador1;
    private javax.swing.JTextField Tjugador2;
    private javax.swing.JTextField Tjugador3;
    private javax.swing.JTextField Tjugador4;
    private javax.swing.JTextField Tjugador5;
    // End of variables declaration//GEN-END:variables
}
